<?php

use Drupal\neg_paragraphs\paragraphs;

function neg_paragraphs_preprocess_paragraph(&$variables){

  $p = new paragraphs();

  $method = 'process_'.$variables['paragraph']->getType();
  if(method_exists($p,$method)) {
    $p->$method($variables);
  }

}

function neg_paragraphs_theme($existing, $type, $theme, $path){
  return array (

    'paragraph__paragraph_row' => array (
      'template' => 'paragraph--row' ,
      'base hook' => 'paragraph',
    ),
    'paragraph__image' => array (
      'template' => 'paragraph--image' ,
      'base hook' => 'paragraph',
    ),
    'paragraph__video' => array (
      'template' => 'paragraph--video' ,
      'base hook' => 'paragraph',
    ),
    'paragraph__text_box' => array (
      'template' => 'paragraph--textbox' ,
      'base hook' => 'paragraph',
    ),
    'paragraph__webform' => array (
      'template' => 'paragraph--webform' ,
      'base hook' => 'paragraph',
    ),

  );
}
