<?php

/**
 * @file
 * Negnet Solutions Paragraphs Module.
 */

use Drupal\neg_paragraphs\ParagraphProcessor;
use Drupal\negnet_utility\FieldUtilities;

/**
 * Implements hook_preprocess_paragraph().
 */
function neg_paragraphs_preprocess_paragraph(&$variables) {

  $p = new ParagraphProcessor();

  $camelType = $variables['paragraph']->getType();
  $method = FieldUtilities::camelCaseString('process_' . $variables['paragraph']->getType());

  if (method_exists($p, $method)) {
    $p->$method($variables);
  }

}

/**
 * Implements hook_theme().
 */
function neg_paragraphs_theme($existing, $type, $theme, $path) {
  return [

    'paragraph__paragraph_row' => [
      'template' => 'paragraph--row' ,
      'base hook' => 'paragraph',
    ],
    'paragraph__image' => [
      'template' => 'paragraph--image' ,
      'base hook' => 'paragraph',
    ],
    'paragraph__video' => [
      'template' => 'paragraph--video' ,
      'base hook' => 'paragraph',
    ],
    'paragraph__text_box' => [
      'template' => 'paragraph--textbox' ,
      'base hook' => 'paragraph',
    ],
    'paragraph__webform' => [
      'template' => 'paragraph--webform' ,
      'base hook' => 'paragraph',
    ],

  ];
}
